
---
title: |
  | ECON 491 - Applied Machine Learning in Economics
  | Final Project (100pts) - due date: Thursday, April  27th
author: "Nonso Osamor (cosamor2) & Victoria Nuñez (vnunez7)"
date: "04/22/2023"
output: html_document
---

---------------------------------------------------------

# Abstract:

This research paper aims to analyze and develop supervised machine learning models that allow us to gain a deeper understanding of the correlation between the physical characteristics of diamonds and the market retail value they hold. In order to further understand the market value of diamonds, we developed several multiple regression models that allow us to understand the influence of shape, carat, symmetry, color, and clarity on the distinct retail cost for the diamond as a commodity. The data set used to construct our model was derived from an outsourcing business client with a need to predict the optimal retail price for particular diamonds based on past sales. The analysis section of our project aims to measure the accuracy of our developed model in predicting an optimal retail price for a diamond product or the commodity itself. The empirical results of our multiple regression models show that there exists a . The results also revealed that the __ of the diamond influences the cost. The implications of this research could emphasize an unspoken criteria between diamond retailers when developing product prices which seem to take diamond characteristics and market value into consideration during the process. Given the numerous characteristics and external market factors that can influence the retail value of a diamond, our research focuses on correlating physical characteristics of the gemstones themselves to the retail cost posted by various retailers. After building multiple regression models and implementing the training data provided, our model built predicts the potential retail cost of a diamond based on the inputted value of its characteristics, which was achieved by implementing a more flexible model that could capture the relationships while using regularization to avoid overfitting to the training data.

# Introduction:

Since the 19th century, diamonds have become one of the most popular and valued gemstones in the world. Diamonds have quickly become a luxury good and several factors play a role in the gemstone's marketability, such as their creation process which can be characterized as natural or synthetic. Developed from the extreme conditions within the Earth's mantle, natural diamonds are formed from the extreme temperatures which is a process that takes over billions of years, which makes their supply extremely low. Diamond retailers have also developed laboratory methods to produce synthetic diamonds, which have a larger demand but have distinctions with natural gemstones. Between synthetic and natural diamonds, the cost of artificially produced diamonds appear to cost cheaper than natural diamonds, which is the result of production costs, availability, and market demand. As jewelers and diamond wholesalers continue to develop retail costs for the commodity, there appears to be an unclear criteria for what conditions of the diamond cause an increase or decrease in value. The cost of jewelry products that contain diamonds and the commodity themselves seem to hold a fluctuating value in the United States economy, which emphasizes several characteristics of the gemstone themselves impact the retail cost. Our project aims to dig deeper into the regressors or potentially influential characteristics of a diamond that lead to a higher market place as a luxury good, and develop a statistical model that would allow us to make predictions about the market value of a diamond based on its physical characteristics.

The several characteristics of diamonds discussed within our project include the shape, carat, symmetry, color, and clarity of diamonds. The shape of diamonds ranges based on the desired appearance of the gemstone and the other characteristics of the diamond desired to included. A carat of a diamond is a term used to describe the weight of the gemstone, with the standard metric conversion being one carat is the equivalent of 0.2 grams or 200 milligrams. The symmetry of a diamond is a characteristic closely related to the shape or cut of the diamond, since the precision of the symmetry of the gemstone is determined by the process in which the diamond is cut into a specified shape. The color of a diamond is graded on a scale of D to Z, with D being the least colorful diamond possible and Z being the most colorful diamond possible. Intuitively, it is easy to assume that a colorless diamond would be the least valuable, but the criteria for grading diamonds emphasizes the antithesis, with colorless diamonds or D graded diamonds being the most valuable due to their ability to allow more light to pass through the gemstone resulting in more brilliance. Lastly, the clarity of the diamond describes the criteria of whether or not a diamond contains internal or external flaws, with the grading scale ranging from flawless to included, or visible inclusions. Diamonds with more flawless grades are upheld to more valuable standards due to their rarity and ability to allow more light to be passed through the gemstone.

# Literature:

The correlation between the physical characteristics of diamonds and their influence on retail price has been analyzed by researchers over the course of the last decade. Several researchers have dove deeper into the impact of online retail availability which can make the gemstone's characteristics not visible to the potential consumer, which can skew results on the correlation between diamond retail costs and characteristics. (Mamonov and Triantoro) The research conducted by Mamonov and Triantoro aimed to find the main physical characteristics that impact diamond prices, which were found to be weight, color, and clarity. On top of this, there has been discourse about the retail price of diamonds and their lack of currency depreciation as a gemstone, which emphasizes a layer of social constructs in the influence of the marketability of the commodity. Besides this, research has also been conducted on the correlation between cut shape and weight of the diamond and the retail price, with results showing that the carat weight of the diamond seems to have the most influential impact on the determined retail price with the shape of the diamond ranked as the second most effective regressor in influencing diamond pricing. (Vaillant and Wolff) After interpreting the empirical results of both research articles, it seems that the weight or carats of the diamond appears to be a recurring regressor with the most influence on predicting the outcome regressand of diamond retail cost.

# Citations:

Mamonov Stanislav, Tamilla Triantoro. “Subjectivity of Diamond Prices in Online Retail: Insights from a Data Mining Study.” Journal of Theoretical and Applied Electronic Commerce Research, vol. 13, no. 2, 2018, pp. 15–28., https://doi.org/10.4067/s0718-18762018000200103. 

Nicolas G. Vaillant, François-Charles Wolff. "Understanding diamond pricing using unconditional quantile regressions." 2013. ⟨halshs-00853384⟩

# Data:

The training data and information on diamonds from various retailers was derived from the 

# Applied:

# Analysis:



